export const clients = [
  { id: "adibuzz", name: "Adibuzz", tag: "@adibuzz", oneWay: true, roundTrip: true, connecting: false },
  { id: "ans", name: "ANS", tag: "@ans", oneWay: true, roundTrip: true, connecting: false },
  { id: "aoshuttle", name: "AO Shuttle", tag: "@aoshuttle", oneWay: true, roundTrip: true, connecting: false },
  { id: "aragon", name: "Aragon", tag: "@aragon", oneWay: true, roundTrip: false, connecting: false },
  { id: "ats", name: "ATS", tag: "@ats", oneWay: true, roundTrip: true, connecting: false },
  { id: "banyumili", name: "Banyumili", tag: "@banyumili", oneWay: true, roundTrip: true, connecting: false },
  { id: "baraya", name: "Baraya", tag: "@baraya", oneWay: true, roundTrip: true, connecting: false },
  { id: "binasarana", name: "Binasarana", tag: "@binasarana", oneWay: true, roundTrip: false, connecting: false },
  { id: "btm", name: "BTM", tag: "@btm", oneWay: true, roundTrip: false, connecting: true },
  { id: "cgtrans", name: "CG Trans", tag: "@cgtrans", oneWay: true, roundTrip: true, connecting: false },
  { id: "ctu", name: "CTU", tag: "@ctu", oneWay: true, roundTrip: true, connecting: false },
  { id: "daytrans", name: "Daytrans", tag: "@daytrans", oneWay: true, roundTrip: false, connecting: true },
  { id: "gracias", name: "Gracias", tag: "@gracias", oneWay: true, roundTrip: true, connecting: false },
  { id: "harumbsi", name: "Harum BSI", tag: "@harumbsi", oneWay: true, roundTrip: true, connecting: false },
  { id: "jackal", name: "Jackal", tag: "@jackal", oneWay: true, roundTrip: true, connecting: false },
  { id: "joglosemar", name: "Joglosemar", tag: "@joglosemar", oneWay: true, roundTrip: true, connecting: false },
  { id: "kpm", name: "KPM", tag: "@kpm", oneWay: true, roundTrip: true, connecting: false },
  { id: "krakaline", name: "Krakaline", tag: "@krakaline", oneWay: true, roundTrip: true, connecting: false },
  { id: "kruzz", name: "Kruzz", tag: "@kruzz", oneWay: true, roundTrip: true, connecting: true },
  { id: "kupuayu", name: "Kupu Ayu", tag: "@kupuayu", oneWay: true, roundTrip: true, connecting: false },
  { id: "marita", name: "Marita", tag: "@marita", oneWay: true, roundTrip: true, connecting: false },
  { id: "minanga", name: "Minanga", tag: "@minanga", oneWay: true, roundTrip: true, connecting: false },
  { id: "mrtrans", name: "MR Trans", tag: "@mrtrans", oneWay: true, roundTrip: false, connecting: false },
  { id: "mstrans", name: "MS Trans", tag: "@mstrans", oneWay: true, roundTrip: true, connecting: false },
  { id: "namaste", name: "Namaste", tag: "@namaste", oneWay: true, roundTrip: true, connecting: false },
  { id: "pelitamas", name: "Pelitamas", tag: "@pelitamas", oneWay: true, roundTrip: true, connecting: false },
  { id: "putraremaja", name: "Putra Remaja", tag: "@putraremaja", oneWay: true, roundTrip: true, connecting: false },
  { id: "raputri", name: "Raputri", tag: "@raputri", oneWay: true, roundTrip: true, connecting: false },
  { id: "riyan", name: "Riyan", tag: "@riyan", oneWay: true, roundTrip: true, connecting: false },
  { id: "royalkencana", name: "Royal Kencana", tag: "@royalkencana", oneWay: true, roundTrip: true, connecting: false },
  { id: "sabila", name: "Sabila", tag: "@sabila", oneWay: true, roundTrip: false, connecting: false },
  { id: "sadya", name: "Sadya", tag: "@sadya", oneWay: true, roundTrip: true, connecting: false },
  { id: "sariharum", name: "Sari Harum", tag: "@sariharum", oneWay: true, roundTrip: true, connecting: false },
  { id: "selamat", name: "Selamat", tag: "@selamat", oneWay: true, roundTrip: false, connecting: false },
  { id: "semeru", name: "Semeru", tag: "@semeru", oneWay: true, roundTrip: false, connecting: false },
  { id: "sunjaya", name: "Sunjaya", tag: "@sunjaya", oneWay: true, roundTrip: true, connecting: false },
  { id: "transkita", name: "Transkita", tag: "@transkita", oneWay: true, roundTrip: true, connecting: false },
  { id: "trikusuma", name: "Trikusuma", tag: "@trikusuma", oneWay: true, roundTrip: true, connecting: false },
  { id: "wbtrans", name: "WB Trans", tag: "@wbtrans", oneWay: true, roundTrip: true, connecting: false },
  { id: "wisatakomodo", name: "Wisata Komodo", tag: "@wisatakomodo", oneWay: true, roundTrip: true, connecting: false },
  { id: "yantigroup", name: "Yanti Group", tag: "@yantigroup", oneWay: true, roundTrip: true, connecting: false },
  { id: "ztrans", name: "Z Trans", tag: "@ztrans", oneWay: true, roundTrip: true, connecting: false },
];