name: Run Playwright Tests

on:
  workflow_dispatch:
    inputs:
      test_file:
        description: "Spec file yang mau dijalankan"
        required: false
        default: ""

      keyword:
        description: "Keyword test title (Playwright --grep)"
        required: false
        default: ""
        
  schedule:
    - cron: "0 23 * * *"

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependecies
        run: npm install

      - name: Install Playwright Browser
        run: npx playwright install chromium

      - name: Set Timezone to WIB
        run: sudo timedatectl set-timezone Asia/Jakarta

      - name: Run tests
        id: run_tests
        run: |
          CMD="npx playwright test"

          if [ -n "${{ github.event.inputs.test_file }}" ]; then
            CMD="$CMD ./tests/${{ github.event.inputs.test_file }}"
          fi

          if [ -n "${{ github.event.inputs.keyword }}" ]; then
            CMD="$CMD --grep '${{ github.event.inputs.keyword }}'"
          fi

          CMD="$CMD --reporter=json --project=chromium"

          echo "Running: $CMD"
          eval "$CMD" > result.json || true
          
        continue-on-error: true

      - name: Build Telegram Report
        run: |
          node <<'EOF'
          const fs = require('fs');

          function formatDuration(ms) {
            const totalSeconds = Math.floor(ms / 1000);
            const hours = Math.floor(totalSeconds / 3600);
            const minutes = Math.floor((totalSeconds % 3600) / 60);
            const seconds = totalSeconds % 60;

            return [
              String(hours).padStart(2, '0'),
              String(minutes).padStart(2, '0'),
              String(seconds).padStart(2, '0'),
            ].join(':');
          }

          const data = JSON.parse(fs.readFileSync('result.json', 'utf8'));
          const suites = data.suites || [];
          const stats = data.stats || {};

          const executionTime = stats.startTime ? new Date(stats.startTime) : new Date();
          const duration = stats.duration || 0;
          const durationFormatted = formatDuration(duration);

          const date = executionTime.toLocaleDateString('id-ID');
          const time = executionTime.toLocaleTimeString('id-ID', { hour12: false });

          let total = 0;
          let passed = 0;
          let failed = 0;
          let flaky = 0;
          let detail = '';

          suites.forEach(suite => {
            if (!suite.file) return;

            detail += `📁 File: ${suite.file}\n`;

            (suite.specs || []).forEach(spec => {
              const test = spec.tests?.[0];
              const results = test?.results || [];
              let status = results.at(-1)?.status || 'unknown';

              if (result.length < 1 && results.some(r => r.status === 'failed') && results.some(r => r.status === 'passed')) {
                status = 'flaky';
              }

              total++;
              
              if (status === 'passed') {
                passed++;
              } else if (status === 'flaky') {
                flaky++;
              } else {
                failed++;
              }

              detail += `  • ${spec.title} — [ ${status} ]\n`;
            });

            detail += '\n';
          });

          const report =
            `AUTOMATE TEST REPORT

             📅 Date: ${date} 
             🕒 Time: ${time}
              ⏱ Duration: ${durationFormatted} ms

             Summary
             🧪 Total: ${total}
             ✅ Passed: ${passed}
             ⚠️ Flaky: ${flaky}
             ❌ Failed: ${failed}

             Detail
             ${detail}`;

          fs.appendFileSync(
            process.env.GITHUB_ENV,
            `TELEGRAM_REPORT<<EOF\n${report}\nEOF\n`
          );
          EOF

      - name: Send Telegram Notification
        if: always()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            --data-urlencode "text=$TELEGRAM_REPORT"

      # - name: Generate HTML report
      #   run: npx playwright show-report --output=report

      # - name: Deploy report to Github Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./report
